import { Changa } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/AuthProvider'
import Navbar from '@/components/Navbar/navbar'
import UserContextProvider from '@/providers/UserContextProvider'
import RTCcontextProvider from '@/providers/rtcProvider'
import "@fortawesome/fontawesome-svg-core/styles.css";
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const changa = Changa({
  subsets : ['latin'],
  weight : ['300','400','500','600','700','800'],
  variable : '--font-changa'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
/>

      </head>
      <body className={changa.variable}>
     <UserContextProvider>   <AuthProvider>
    <RTCcontextProvider> 
     <Navbar/>
        {children}
        </RTCcontextProvider>
        </AuthProvider>
        </UserContextProvider> 
        </body>

    </html>
  )
}
